### PR TITLE
Issue #96 - Add resolvePath attribute to App

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Hey @eduardolundgren, <br /><br /> Here is an update for https://github.com/eduardolundgren/senna/issues/96<br /><br /> Let me know if this is what you were talking about or not. I applied this to use in our project and all i had to do was add

```javascript
app.resolvePath = function(path) {
	return path + '&p_p_isolated=1';
};
```

and it worked great.

### CODE REVIEW

**Comment by eduardolundgren** [comment]
LGTM, missing tests only. Could you add them before merge? Thank you.

**Comment by bryceosterhaus** [comment]
Added new test for resolvePath attribute on App

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by eduardolundgren** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/eduardolundgren/senna/compare/b956b3a~1...b956b3a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
